module.exports = {
  INITIAL: `INITIAL`,
  API_CALL : `API_CALL`,
  API_TEST_START : `API_TEST_START`,
  API_TEST_SUCCESS : `API_TEST_SUCCESS`,
  API_TEST_FAILTURE : `API_TEST_FAILTURE`,
  SPECIFIC_ACTION : `SPECIFIC_ACTION`
};